### ISSUE TITLE
Action unable to listen to events not tied to an action

### ISSUE THREAD

**Issue by thorwe** [XeroxDev/Stream-Deck-TS-SDK#15]
I was trying to listen to didReceiveGlobalSettings on an action via decorator to no avail, setupReady was affected, too.
So I went looking for 'global' event handling.

Debug logging
https://github.com/XeroxDev/Stream-Deck-TS-SDK/blob/89831d0939b41531dafc8ef2f20425bb21f826a3/src/abstracts/stream-deck-handler-base.ts#L298
showed it coming in, leading to
https://github.com/XeroxDev/Stream-Deck-TS-SDK/blob/89831d0939b41531dafc8ef2f20425bb21f826a3/src/manager/event.manager.ts#L82
being called with * as actionName.

So far so good, the culprit appears to be:
https://github.com/XeroxDev/Stream-Deck-TS-SDK/blob/89831d0939b41531dafc8ef2f20425bb21f826a3/src/manager/event.manager.ts#L49

The callback ...call from callEvents makes the eventActionName parameter an asterisk, which would only fit a register via asterisk - the condition check is against actionName being asterisk (here it is the actual actionName used to register for the event) or eventActionName being false. Neither applies, hence event doesn't trigger.

I'm not super sure if the intend here is `actionName === '*' || eventActionName === '*'` or `eventActionName === '*'` - or, ofc if I'm just not getting sth. in the first place.

**Comment by XeroxDev** [comment]
Hello! Thank you for opening a issue. I'll look into it ASAP.

Could you send me some snippets from you as example, so I can look better into it or do you have a public repository?

**Comment by thorwe** [comment]
https://github.com/thorwe/Stream-Deck-TS-SDK/tree/issue-15

Please note it's just demonstrating the issue and two possible fixes - I'm not deep enough into the code to make a decision there and come up with a pull req.

**Comment by XeroxDev** [comment]
Thanks for the detailed fork and possible fix solutions. Now it should be simple to fix this issue!
