### ISSUE TITLE
Missing step

### ISSUE THREAD

**Issue by elementalTIMING** [XeroxDev/Stream-Deck-TS-SDK#16]
Hi,

sorry if this will be a bit off-topic but I hope you can help. I took a look to the SDK and it really looks promising. But my questions is: after I compiled the TS code into JS - How can I create a streamDeckPlugin out of this code?

Thx for your help!

**Comment by XeroxDev** [comment]
Hey! After it's compiled into javascript, you can generate your plugin file in the same way as with a vanilla javascript project. The [packaging](https://docs.elgato.com/sdk/plugins/packaging) docs of Elgato should help you with it.
